title: MCP Security Scanner
description: A comprehensive security vulnerability scanner for MCP servers and plugins
theme: jekyll-theme-cayman

baseurl: "/mcp-security-scanner"
url: "https://dmontgomery40.github.io"

plugins:
  - jekyll-seo-tag